name: dotnet test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      working-directory: test/Permify.AspNetCore.Tests
      run: dotnet restore
    - name: Run tests
      working-directory: test/Permify.AspNetCore.Tests
      run: dotnet test
