name: dotnet test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bufbuild/buf-setup-action@v1.11.0

    - name: Generate Protobuf files
      run: buf generate --include-imports
      working-directory: src/Permify.AspNetCore/Protos

    - name: Restore dependencies
      working-directory: test/Permify.AspNetCore.Tests
      run: dotnet restore
      
    - name: Run tests
      working-directory: test/Permify.AspNetCore.Tests
      run: dotnet test
